<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Test Extension</text>

        <Action name="myActionaaaa">
        <icon></icon>
        <text>Tests the extension</text>
        <whatsThis>Tests the extension</whatsThis>
        <toolTip>Tests the extension</toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+alt+shift+p</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>